spring:
  datasource:
    url: ${URL}
    username: ${USER}
    password: ${PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  session:
    jdbc:
      initialize-schema: always
  devtools:
    restart:
      enabled: true

server:
  address: localhost
  port: 8080
